### ISSUE TITLE
Add checksums API

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-APIs#16]
See: https://forums.classicpress.net/t/classicpress-checksums-api/1596

Please leave other links and information here.

**Comment by invisnet** [comment]
It's a pretty simple process once we've got our PKI sorted out:

1. `git pull` on ClassicPress-release
1. `git --verify-tag` _tag_
1. export the hashes
1. sign the hash file with CP-issued cert
1. put hashes and signature on API server

The only real decision is whether we automate this, or add it as a manual step to the release process. There are pros and cons to each - the forum is a better place to discuss the details.

**Comment by nylen** [comment]
Why should the implementation of just this API endpoint wait for our PKI to be in place? Seems like there's no harm in adding that later.

**Comment by invisnet** [comment]
Right now we don't make any claims about being able to validate anything that's not on GitHub. Someone could hijack the API server and that'd really suck, but _technically_ there's nothing of intrinsic value on there, and users could fix things by getting the zip directly from GitHub. (I did say it'd suck).

If we put hashes on there we're implicitly saying "you can trust these", but that's not a claim we can justify without a signature the existing CP instance can validate.

**Comment by nylen** [comment]
People are asking for this already, so I think we should make it available.

I am all for waiting until we can sign our API responses to actually use the hashes in core. These two tasks are mostly independent.
