### ISSUE TITLE
Add API endpoint for feature votes

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress-APIs#3]
Let's build out a basic API endpoint that shows data from https://vote.classicpress.net/.  We'll use this in the dashboard to replace WordPress events.

The response data should have three sections: `most_wanted`, `trending`, and `recent`, matching the data on the site.

For now, the endpoint can just be a static response like the others.  This will be enough to proceed with the UI implementation.

See also: https://github.com/ClassicPress/ClassicPress/issues/40

**Comment by johnalarcon** [comment]
Can these endpoints be built against? If so, might they also be added to the readme of the [APIs](https://github.com/ClassicPress/ClassicPress-APIs)?

**Comment by nylen** [comment]
They can't be built against directly, because they don't support CORS for in-browser usage.  Also we want to build a proxy endpoint that fetches data from there, because we may change the implementation of the voting platform later.

**Comment by brettvan** [comment]
Seems like a workable approach would be to proxy the requests through the CP API domain and respond with the proper CORS headers. Is the Fider installation self hosted or via their service?  I'd like to help with this one.

**Comment by nylen** [comment]
Yep, that's the approach I would use here.

Fider is hosting this for us.

I wouldn't worry about caching for a first pass either, Cloudflare can handle this for us.

**Comment by brettvan** [comment]
Thanks, just got to that part in the changes with the call to wp_dashboard_cached_rss_widget ...

**Comment by nylen** [comment]
Done in #7 and 3956adfe6bde32ef0b7904ea13b100bfd7127ec1.
